services:
  polyglots-api-vps1:
    image: polyglots-api:local
    container_name: polyglots-api-local-1
    build:
      context: .
      dockerfile: src/Presentation/Polyglots.Presentation.WebAPI/Dockerfile
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=${DB_HOST};Port=${DB_PORT};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
      - Redis__Configuration=${REDIS_HOST}:${REDIS_PORT}

  polyglots-api-vps2:
    image: polyglots-api:local
    container_name: polyglots-api-local-2
    build:
      context: .
      dockerfile: src/Presentation/Polyglots.Presentation.WebAPI/Dockerfile
    ports:
      - "8082:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=${DB_HOST};Port=${DB_PORT};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
      - Redis__Configuration=${REDIS_HOST}:${REDIS_PORT}

  polyglots-api-vps3:
    image: polyglots-api:local
    container_name: polyglots-api-local-3
    build:
      context: .
      dockerfile: src/Presentation/Polyglots.Presentation.WebAPI/Dockerfile
    ports:
      - "8083:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=${DB_HOST};Port=${DB_PORT};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
      - Redis__Configuration=${REDIS_HOST}:${REDIS_PORT}

networks:
  polyglots_network:
    name: polyglots_shared_network
    external: true