events { worker_connections 1024; }

http {
    # Definimos el grupo de servidores (upstream) usando los nombres internos de Docker
    upstream polyglots_apis {
        server polyglots-api-local-1:8080;
        server polyglots-api-local-2:8080;
        server polyglots-api-local-3:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://polyglots_apis;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}